-- =============================================================
-- BASE DE DATOS: BANCO CORE Y TICKETPREMIUM FIFA WORLD CUP 2026
-- MOTOR: MySQL (InnoDB)
-- =============================================================

DROP DATABASE IF EXISTS ticketpremium_db;
DROP DATABASE IF EXISTS banco_core_db;

CREATE DATABASE banco_core_db CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE ticketpremium_db CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- -------------------------------------------------------------
-- BANCO CORE SCHEMA
-- -------------------------------------------------------------
USE banco_core_db;

CREATE TABLE CLIENTE (
    COD_CLIENTE INT NOT NULL AUTO_INCREMENT,
    CEDULA VARCHAR(100) NOT NULL UNIQUE,
    NOMBRE VARCHAR(100) NOT NULL,
    GENERO VARCHAR(1) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE)
) ENGINE=InnoDB;

CREATE TABLE CUENTA (
    NUM_CUENTA VARCHAR(8) NOT NULL,
    COD_CLIENTE INT NOT NULL,
    SALDO DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    CONSTRAINT PK_CUENTA PRIMARY KEY (NUM_CUENTA),
    CONSTRAINT FK_CUENTA_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE MOVIMIENTO (
    COD_MOVIMIENTO INT NOT NULL AUTO_INCREMENT,
    NUM_CUENTA VARCHAR(8) NOT NULL,
    TIPO VARCHAR(3) NOT NULL, -- 'DEP' o 'RET'
    VALOR DECIMAL(10,2) NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT PK_MOVIMIENTO PRIMARY KEY (COD_MOVIMIENTO),
    CONSTRAINT FK_MOVIMIENTO_CUENTA FOREIGN KEY (NUM_CUENTA) REFERENCES CUENTA(NUM_CUENTA) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CREDITO (
    ID_CREDITO INT NOT NULL AUTO_INCREMENT,
    COD_CLIENTE INT NOT NULL,
    NUM_CUENTA VARCHAR(8) NOT NULL,
    MONTO_PRESTAMO DECIMAL(10,2) NOT NULL,
    INTERES_ANUAL DECIMAL(5,2) NOT NULL DEFAULT 16.50,
    PLAZO_MESES INT NOT NULL,
    CUOTA_MENSUAL DECIMAL(10,2) NOT NULL,
    FECHA_APROBACION DATE NOT NULL,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'APROBADO',
    CONSTRAINT PK_CREDITO PRIMARY KEY (ID_CREDITO),
    CONSTRAINT FK_CREDITO_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE) ON DELETE CASCADE,
    CONSTRAINT FK_CREDITO_CUENTA FOREIGN KEY (NUM_CUENTA) REFERENCES CUENTA(NUM_CUENTA) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE TABLA_AMORTIZACION (
    ID_AMORTIZACION INT NOT NULL AUTO_INCREMENT,
    ID_CREDITO INT NOT NULL,
    NUM_CUOTA INT NOT NULL,
    VALOR_CUOTA DECIMAL(10,2) NOT NULL,
    INTERES_PAGADO DECIMAL(10,2) NOT NULL,
    CAPITAL_PAGADO DECIMAL(10,2) NOT NULL,
    SALDO DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_TABLA_AMORTIZACION PRIMARY KEY (ID_AMORTIZACION),
    CONSTRAINT FK_AMORTIZACION_CREDITO FOREIGN KEY (ID_CREDITO) REFERENCES CREDITO(ID_CREDITO) ON DELETE CASCADE
) ENGINE=InnoDB;


-- -------------------------------------------------------------
-- TICKETPREMIUM SCHEMA
-- -------------------------------------------------------------
USE ticketpremium_db;

CREATE TABLE PAIS (
    ID_PAIS INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT PK_PAIS PRIMARY KEY (ID_PAIS)
) ENGINE=InnoDB;

CREATE TABLE ESTADIO (
    ID_ESTADIO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    CIUDAD VARCHAR(100) NOT NULL,
    ID_PAIS INT NOT NULL,
    CAPACIDAD INT NOT NULL,
    CONSTRAINT PK_ESTADIO PRIMARY KEY (ID_ESTADIO),
    CONSTRAINT FK_ESTADIO_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE EQUIPO (
    ID_EQUIPO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    ID_PAIS INT NOT NULL,
    CONSTRAINT PK_EQUIPO PRIMARY KEY (ID_EQUIPO),
    CONSTRAINT FK_EQUIPO_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
    CEDULA VARCHAR(20) NOT NULL UNIQUE,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
) ENGINE=InnoDB;

CREATE TABLE PARTIDO_FUTBOL (
    CODIGO INT NOT NULL AUTO_INCREMENT,
    ID_EQUIPO_LOCAL INT NOT NULL,
    ID_EQUIPO_VISITA INT NOT NULL,
    FECHA DATETIME NOT NULL,
    ID_ESTADIO INT NOT NULL,
    GRUPO VARCHAR(2) NOT NULL,
    CONSTRAINT PK_PARTIDO_FUTBOL PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PARTIDO_LOCAL FOREIGN KEY (ID_EQUIPO_LOCAL) REFERENCES EQUIPO(ID_EQUIPO) ON DELETE RESTRICT,
    CONSTRAINT FK_PARTIDO_VISITA FOREIGN KEY (ID_EQUIPO_VISITA) REFERENCES EQUIPO(ID_EQUIPO) ON DELETE RESTRICT,
    CONSTRAINT FK_PARTIDO_ESTADIO FOREIGN KEY (ID_ESTADIO) REFERENCES ESTADIO(ID_ESTADIO) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE LOCALIDAD_PARTIDO (
    ID INT NOT NULL AUTO_INCREMENT,
    CODIGO_PARTIDO INT NOT NULL,
    CODIGO_LOCALIDAD VARCHAR(50) NOT NULL,
    DISPONIBILIDAD INT NOT NULL DEFAULT 0,
    PRECIO DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_LOCALIDAD_PARTIDO PRIMARY KEY (ID),
    CONSTRAINT FK_LOCALIDAD_PARTIDO FOREIGN KEY (CODIGO_PARTIDO) REFERENCES PARTIDO_FUTBOL(CODIGO) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ASIENTO (
    ID_ASIENTO INT NOT NULL AUTO_INCREMENT,
    ID_ESTADIO INT NOT NULL,
    SECCION VARCHAR(50) NOT NULL, -- 'PALCO', 'TRIBUNA', 'GENERAL'
    FILA VARCHAR(5) NOT NULL,
    NUMERO INT NOT NULL,
    CONSTRAINT PK_ASIENTO PRIMARY KEY (ID_ASIENTO),
    CONSTRAINT FK_ASIENTO_ESTADIO FOREIGN KEY (ID_ESTADIO) REFERENCES ESTADIO(ID_ESTADIO) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE FACTURA (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    FECHA DATETIME NOT NULL,
    SUBTOTAL DECIMAL(10,2) NOT NULL,
    DESCUENTO DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    IVA DECIMAL(10,2) NOT NULL,
    TOTAL DECIMAL(10,2) NOT NULL,
    FORMA_PAGO VARCHAR(20) NOT NULL, -- 'EFECTIVO', 'CREDITO'
    ID_CREDITO INT NULL,
    CONSTRAINT PK_FACTURA PRIMARY KEY (ID),
    CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE DETALLE_FACTURA (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_FACTURA INT NOT NULL,
    CODIGO_PARTIDO INT NOT NULL,
    CODIGO_LOCALIDAD VARCHAR(50) NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    SUBTOTAL DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY (ID),
    CONSTRAINT FK_DETALLE_FACTURA FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_PARTIDO FOREIGN KEY (CODIGO_PARTIDO) REFERENCES PARTIDO_FUTBOL(CODIGO) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE ASIENTO_PARTIDO (
    ID_ASIENTO_PARTIDO INT NOT NULL AUTO_INCREMENT,
    CODIGO_PARTIDO INT NOT NULL,
    ID_ASIENTO INT NOT NULL,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'DISPONIBLE', -- 'DISPONIBLE', 'RESERVADO', 'OCUPADO'
    ID_DETALLE_FACTURA INT NULL,
    NOMBRE_OCUPANTE VARCHAR(100) NULL,
    FECHA_RESERVA DATETIME NULL,
    CONSTRAINT PK_ASIENTO_PARTIDO PRIMARY KEY (ID_ASIENTO_PARTIDO),
    CONSTRAINT FK_AP_PARTIDO FOREIGN KEY (CODIGO_PARTIDO) REFERENCES PARTIDO_FUTBOL(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_AP_ASIENTO FOREIGN KEY (ID_ASIENTO) REFERENCES ASIENTO(ID_ASIENTO) ON DELETE CASCADE,
    CONSTRAINT FK_AP_DETALLE FOREIGN KEY (ID_DETALLE_FACTURA) REFERENCES DETALLE_FACTURA(ID) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE USUARIO (
    ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID)
) ENGINE=InnoDB;
